batch_shipyard:
  storage_account_settings: shipyard
global_resources:
  volumes:
    shared_data_volumes:
      datablob_vol:
        volume_driver: azureblob
        storage_account_settings: datalake1
        azure_blob_container_name: aiforearth
        container_path: ${AZ_BATCH_NODE_SHARED_DIR}/aiforearth
        mount_options:
          - --use-https=true
        bind_options: rw
  docker_images:
    - aiforearth2020/utils
    - aiforearth2020/sra-toolkit
    - aiforearth2020/bbtools
    - aiforearth2020/spades
    - aiforearth2020/megahit
    - aiforearth2020/bowtie2
    - aiforearth2020/htslib
    - aiforearth2020/metabat2
    - aiforearth2020/checkm
