batch_shipyard:
  storage_account_settings: shipyard
global_resources:
  volumes:
    shared_data_volumes:
      datablob_vol:
        volume_driver: azureblob
        storage_account_settings: data
        azure_blob_container_name: data
        container_path: ${AZ_BATCH_NODE_SHARED_DIR}/data
        mount_options:
          - --use-https=true
        bind_options: rw
  docker_images:
    - metashot/utils:1.0.0-1
    - metashot/sra-toolkit:2.9.2-1
    - metashot/bbtools:38.79-1
    - metashot/spades:3.14.0-1
    - metashot/megahit:1.2.9-1
    - metashot/bowtie2:2.3.4.3-1
    - metashot/htslib:1.9-1
    - metashot/metabat2:2.12.1-1
    - metashot/checkm:1.1.2-1
