job_specifications:
- id: {{ sra_accession }}-sraassembly-job
  shared_data_volumes:
    - datablob_vol
  tasks:
    - id: {{ sra_accession }}-download-task
      docker_image: aiforearth2020/sra-toolkit
      resource_files:
        - blob_source: https://raw.githubusercontent.com/compmetagen/AIforEarth2020/master/shipyard/scripts/download.sh
          file_path: download.sh
      command: download.sh {{ sra_accession }}
    - id: {{ sra_accession }}-clean-task
      docker_image: aiforearth2020/bbtools
      resource_files:
        - blob_source: https://raw.githubusercontent.com/compmetagen/AIforEarth2020/master/shipyard/scripts/clean.sh
          file_path: clean.sh
      command: clean.sh {{ sra_accession }}
      depends_on:
        - {{ sra_accession }}-download-task
    - id: {{ sra_accession }}-assembly-task
      docker_image: aiforearth2020/spades
      resource_files:
        - blob_source: https://raw.githubusercontent.com/compmetagen/AIforEarth2020/master/shipyard/scripts/assemble.sh
          file_path: assemble.sh
      command: assembly.sh {{ sra_accession }}
      depends_on: 
        - {{ sra_accession }}-clean-task

            